SHOW DATABASES;

SHOW SCHEMAS;

SHOW TABLES IN SCHEMA COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC;

DESC TABLE COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES;

SELECT COUNT(*) AS total_rows
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES;

SELECT *
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES
LIMIT 20;

-- date range
SELECT
    MIN(DATE),
    MAX(DATE)
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES;

-- missing values
SELECT
    COUNT(*) - COUNT(COUNTRY_REGION) AS country_null_val,
    COUNT(*) - COUNT(DATE) AS date_null_val,
    COUNT(*) - COUNT(CASE_TYPE) AS case_type_null_val,
    COUNT(*) - COUNT(CASES) AS cases_null_val
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES;

-- reason of missing values
SELECT
    CASE_TYPE,
    COUNT(*) AS total_rows,
    COUNT(*) - COUNT(CASES) AS missing_cases
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES
GROUP BY CASE_TYPE;

SELECT
    COUNTRY_REGION,
    COUNT(*) AS missing_recovered
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES
WHERE CASE_TYPE = 'Recovered'
AND CASES IS NULL
GROUP BY COUNTRY_REGION
ORDER BY missing_recovered DESC
LIMIT 20;

SELECT
    COUNTRY_REGION,
    COUNT(*) AS missing_confirmed
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES
WHERE CASE_TYPE = 'Confirmed'
AND CASES IS NULL
GROUP BY COUNTRY_REGION
ORDER BY missing_confirmed DESC
LIMIT 20;

SELECT
    COUNTRY_REGION,
    COUNT(*) AS missing_deaths
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES
WHERE CASE_TYPE = 'Deaths'
AND CASES IS NULL
GROUP BY COUNTRY_REGION
ORDER BY missing_deaths DESC
LIMIT 20;

SELECT
    DATE,
    PROVINCE_STATE,
    COUNTY
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES
WHERE COUNTRY_REGION = 'Canada'
AND CASES IS NULL
ORDER BY DATE;

-- duplicates
SELECT
    *,
    COUNT(*) AS duplicate_count
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES
GROUP BY ALL
HAVING COUNT(*) > 1;

SELECT
    DATE,
    COUNTRY_REGION,
    PROVINCE_STATE,
    COUNTY,
    CASE_TYPE,
    COUNT(*) AS total
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES
GROUP BY
    DATE,
    COUNTRY_REGION,
    PROVINCE_STATE,
    COUNTY,
    CASE_TYPE
HAVING COUNT(*) > 1;

-- join readiness
SELECT
    COUNT(DISTINCT COUNTRY_REGION) AS unique_countries,
    COUNT(*) - COUNT(COUNTRY_REGION) AS missing_country
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19_TIMESERIES;