SHOW DATABASES;

USE DATABASE COVID19_EPIDEMIOLOGICAL_DATA;
SHOW SCHEMAS;

SHOW TABLES;

DESCRIBE TABLE COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19;

SELECT DISTINCT COUNTRY_REGION
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19
ORDER BY COUNTRY_REGION;

SELECT DISTINCT COUNTRY
FROM COVID_PROJECT.PUBLIC.DEMOGRAPHICS
ORDER BY COUNTRY;

CREATE OR REPLACE TABLE COVID_PROJECT.PUBLIC.DEMOGRAPHICS_CLEAN AS
SELECT
UPPER(TRIM(COUNTRY)) AS COUNTRY,
YEAR,
POPULATION,
NET_MIGRATION,
POPULATION_IN_MILLIONS
FROM COVID_PROJECT.PUBLIC.DEMOGRAPHICS
WHERE COUNTRY IS NOT NULL
AND TRIM(COUNTRY) <> ''
AND YEAR >= 2020
AND POPULATION IS NOT NULL
AND POPULATION > 0;

CREATE OR REPLACE TABLE COVID_PROJECT.PUBLIC.COVID_CLEAN AS
SELECT
UPPER(TRIM(COUNTRY_REGION)) AS COUNTRY,
DATE,
YEAR(DATE) AS YEAR,
LOWER(TRIM(CASE_TYPE)) AS CASE_TYPE,
CASES,
DIFFERENCE,
LAT,
LONG
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19
WHERE COUNTRY_REGION IS NOT NULL
AND TRIM(COUNTRY_REGION) <> ''
AND DATE IS NOT NULL
AND CASES IS NOT NULL
AND UPPER(TRIM(COUNTRY_REGION)) NOT IN (
    'CRUISE SHIP',
    'MS ZAANDAM',
    'SUMMER OLYMPICS 2020',
    'WINTER OLYMPICS 2022',
    'ANTARCTICA',
    'HOLY SEE (VATICAN CITY STATE)',
    'GUERNSEY',
    'JERSEY',
    'REUNION'
);

SELECT DISTINCT cov.COUNTRY
FROM COVID_PROJECT.PUBLIC.COVID_CLEAN cov
LEFT JOIN COVID_PROJECT.PUBLIC.DEMOGRAPHICS_CLEAN demogr
ON cov.COUNTRY = demogr.COUNTRY
AND cov.YEAR = demogr.YEAR
WHERE demogr.COUNTRY IS NULL
ORDER BY cov.COUNTRY;

CREATE OR REPLACE TABLE COVID_PROJECT.PUBLIC.COUNTRY_MAPPING (
    SOURCE_COUNTRY STRING,
    STANDARD_COUNTRY STRING
);

INSERT INTO COVID_PROJECT.PUBLIC.COUNTRY_MAPPING VALUES
('BAHAMAS, THE','BAHAMAS'),
('CAPE VERDE','CABO VERDE'),
('EAST TIMOR','TIMOR-LESTE'),
('GAMBIA','THE GAMBIA'),
('SYRIA','SYRIAN ARAB REPUBLIC');

CREATE OR REPLACE TABLE COVID_PROJECT.PUBLIC.COVID_DAILY AS
SELECT
COALESCE(m.STANDARD_COUNTRY, c.COUNTRY) AS COUNTRY,
c.DATE,
c.YEAR,
SUM(CASE 
WHEN c.CASE_TYPE='confirmed'
THEN c.CASES 
ELSE 0 
END) AS CONFIRMED,
SUM(CASE 
WHEN c.CASE_TYPE='deaths'
THEN c.CASES 
ELSE 0 
END) AS DEATHS,
SUM(CASE 
WHEN c.CASE_TYPE='recovered'
THEN c.CASES 
ELSE 0 
END) AS RECOVERED,
SUM(CASE 
WHEN c.CASE_TYPE='active'
THEN c.CASES 
ELSE 0 
END) AS ACTIVE
FROM COVID_PROJECT.PUBLIC.COVID_CLEAN c
LEFT JOIN COVID_PROJECT.PUBLIC.COUNTRY_MAPPING m
ON c.COUNTRY = m.SOURCE_COUNTRY
GROUP BY
COALESCE(m.STANDARD_COUNTRY, c.COUNTRY),
c.DATE,
c.YEAR;